runtime: java21 # Ou java11, java21 dependendo da sua versão
instance_class: F1 # Define o tamanho da máquina (F1 é a menor/mais barata)

# O comando para iniciar sua aplicação.
# Ajuste o nome 'minha-app-0.0.1-SNAPSHOT.jar' para o nome real do seu arquivo
entrypoint: java -jar target/appChurch.jar