spring.application.name=appChurch

#spring.datasource.url = jdbc:postgresql://localhost:5432/dbChurch
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=gen-lang-client-0788356664:southamerica-east1:postgresql&socketFactory=com.google.cloud.sql.postgres.SocketFactory

spring.datasource.url=jdbc:postgresql://ep-dark-salad-acru5w6x.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SEgcwDi6qH7K
spring.jpa.hibernate.ddl-auto=update

# InfinitePay Config
infinitepay.url=https://api.infinitepay.io/invoices/public/checkout/links
infinitepay.token=SEU_TOKEN_DE_PRODUCAO_AQUI
infinitepay.handle=harison-nunes
infinitepay.redirect-base=https://ecclesia-manager-ten.vercel.app/evento
infinitepay.webhook-url=https://gen-lang-client-0788356664.rj.r.appspot.com/api/webhooks/infinitepay


# --- OBSERVABILIDADE & ACTUATOR ---
# Expor endpoints de saúde e métricas
management.endpoints.web.exposure.include=health,info,metrics,loggers

# Mostrar detalhes completos do erro no health check (cuidado em produção, usar 'never' se for público)
management.endpoint.health.show-details=always

# --- LOGS ---
# Nível de log geral
logging.level.root=INFO
# Ver logs da sua aplicação com mais detalhes
logging.level.com.church.appChurch=DEBUG
# Ver queries SQL do Hibernate (Opcional, bom para debug)
logging.level.org.hibernate.SQL=DEBUG
# Ver os parâmetros das queries (?, ?, ?)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Formato do Log (O Spring Boot 3 com Micrometer já inclui traceId automaticamente se configurado)
# Se não aparecer, você pode forçar com:
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId} spanId=%X{spanId}] - %msg%n