spring.application.name=appChurch

#spring.datasource.url = jdbc:postgresql://localhost:5432/dbChurch
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=gen-lang-client-0788356664:southamerica-east1:postgresql&socketFactory=com.google.cloud.sql.postgres.SocketFactory

#producao
#spring.datasource.url=jdbc:postgresql://ep-dark-salad-acru5w6x.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
#dev
spring.datasource.url=jdbc:postgresql://ep-soft-tooth-ac92jkw4-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SEgcwDi6qH7K
spring.jpa.hibernate.ddl-auto=update

# InfinitePay Config
infinitepay.url=https://api.infinitepay.io/invoices/public/checkout/links
infinitepay.token=SEU_TOKEN_DE_PRODUCAO_AQUI
infinitepay.handle=jpa_cncs
infinitepay.redirect-base=https://ecclesia-manager-ten.vercel.app/evento
infinitepay.webhook-url=https://ecclesiamanager-1098108839645.us-central1.run.app/api/webhooks/infinitepay

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always
logging.level.root=INFO
logging.level.com.church.appChurch=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n