spring.application.name=appChurch

#spring.datasource.url = jdbc:postgresql://localhost:5432/dbChurch
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=gen-lang-client-0788356664:southamerica-east1:postgresql&socketFactory=com.google.cloud.sql.postgres.SocketFactory

#producao
spring.datasource.url=${DB_URL}
#dev
#spring.datasource.url=jdbc:postgresql://ep-soft-tooth-ac92jkw4-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# InfinitePay Config
infinitepay.url=https://api.infinitepay.io/invoices/public/checkout/links
infinitepay.token=SEU_TOKEN_DE_PRODUCAO_AQUI
infinitepay.handle=jpa_cncs
infinitepay.redirect-base=${FRONTEND_URL}
infinitepay.webhook-url=${WEBHOOK_URL}

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always
logging.level.root=INFO
logging.level.com.church.appChurch=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId} spanId=%X{spanId}] - %msg%n